### PR TITLE
added libfreetype submodule

### PR DESCRIPTION
**Pull request by PaulBatchelor**
Can this PR be verified before merging? I actually haven't yet set up my cross compilation environment, so I can't easily test anything yet.

### CODE REVIEW

**Comment by PaulBatchelor** [comment]
This should fix #3

**Comment by canselcik** [comment]
Thanks for taking care of this. Would you be able to rebase with the latest changes before I merge it?

**Comment by PaulBatchelor** [comment]
Sure I think I can do that.

**Comment by PaulBatchelor** [comment]
@canselcik rebased what I could, but I ended up having to do a small merge for some reason afterwards. Hope that's okay.

**Pull request merged**
